### ISSUE TITLE
Продакшн сайт не отвечает

### ISSUE THREAD

**Issue by qelphybox** [qelphybox/hakeshonassybot#429]
У нас на проде должен быть сайт https://hakeshonassy.tk/. Домен еще действует. DNS запись смотрит на 158.101.173.106 и сервер сам работает, но сервак по этому адресу не отвечает

**Comment by MikhailBystrov** [comment]
Привет, беру задачу.

**Comment by MikhailBystrov** [comment]
Из того, что пока что нашёл.


Не запускается и рестартует сервис api по ошибке ниже:
<details>
  <summary>api log</summary>
  
_hakeshonassybot@1.0.0 api /app
node src/api/index.js_

/app/node_modules/mongodb-connection-string-url/lib/index.js:47
        const match = uri.match(HOSTS_REGEX);
                          ^
TypeError: Cannot read property 'match' of undefined
    at new ConnectionString (/app/node_modules/mongodb-connection-string-url/lib/index.js:47:27)
    at Object.parseOptions (/app/node_modules/mongodb/lib/connection_string.js:209:17)
    at new MongoClient (/app/node_modules/mongodb/lib/mongo_client.js:62:46)
    at new DBClient (/app/src/dbClient.js:7:19)
    at Object.<anonymous> (/app/src/dbClient.js:31:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hakeshonassybot@1.0.0 api: `node src/api/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hakeshonassybot@1.0.0 api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-20T16_50_07_231Z-debug.log
  
</details>

Мб джависты подскажут, если им знакома эта ошибка?
